# Generated by Django 3.1.4 on 2021-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapps', '0002_place_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='placen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picture')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('subname', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
